### ISSUE TITLE
install sentencepiece error

### ISSUE THREAD

**Issue by scavru** [janvarev/OneRingTranslator-installer#2]
`Collecting sentencepiece<0.2.0,>=0.1.96 (from unbabel-comet->-r requirements-bleu.txt (line 4))
  Using cached sentencepiece-0.1.99.tar.gz (2.6 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "F:\TEMP\pip-install-ts6exy8u\sentencepiece_6052ea11c04e4de8a09437a3ef4eb9ac\setup.py", line 126, in <module>
          subprocess.check_call([
        File "E:\textmodels\OneRingTranslator-installer\installer_files\env\Lib\subprocess.py", line 408, in check_call
          retcode = call(*popenargs, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "E:\textmodels\OneRingTranslator-installer\installer_files\env\Lib\subprocess.py", line 389, in call
          with Popen(*popenargs, **kwargs) as p:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "E:\textmodels\OneRingTranslator-installer\installer_files\env\Lib\subprocess.py", line 1026, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "E:\textmodels\OneRingTranslator-installer\installer_files\env\Lib\subprocess.py", line 1538, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [WinError 2] Не удается найти указанный файл
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Press any key to continue . . .
`

**Comment by VitaliyAT** [comment]
any news about this problem?

**Comment by blackmesataiwan** [comment]
Try to modify `install.bat`  to install python 3.11 version.

from:
```cmd
set "PACKAGES_TO_INSTALL=pytorch torchvision torchaudio cpuonly transformers git"
```
to
```cmd
set "PACKAGES_TO_INSTALL=python=3.11.9 pytorch torchvision torchaudio transformers git"
```
